### ISSUE TITLE
Specify the array filter criteria.

### ISSUE THREAD

**Issue by fedorchukivan** [zvierievkp31ms/MIPZ#1]
It is not clear what is the criteria of filtering the array. Is it undefined, false or zero values that are expected to be cut off. Should be specified.
https://github.com/zvierievkp31ms/MIPZ/blob/bb67addd1ff9263a540145cd02a78cd3108a0774/practice_1/file.ts#L28

**Comment by zvierievkp31ms** [comment]
exception data can be undefined or [NaN], the necessary changes have been made to specify this filter in more detail
