### ISSUE TITLE
Replace harcoded values with constant variables.

### ISSUE THREAD

**Issue by fedorchukivan** [zvierievkp31ms/MIPZ#2]
Should replace hardcoded values with properly named constant values in the following lines to increase code maintainability and make it more clear for understanding.
https://github.com/zvierievkp31ms/MIPZ/blob/bb67addd1ff9263a540145cd02a78cd3108a0774/practice_1/main.ts#L26
https://github.com/zvierievkp31ms/MIPZ/blob/bb67addd1ff9263a540145cd02a78cd3108a0774/practice_1/main.ts#L33
https://github.com/zvierievkp31ms/MIPZ/blob/bb67addd1ff9263a540145cd02a78cd3108a0774/practice_1/main.ts#L44
https://github.com/zvierievkp31ms/MIPZ/blob/bb67addd1ff9263a540145cd02a78cd3108a0774/practice_1/main.ts#L45
https://github.com/zvierievkp31ms/MIPZ/blob/bb67addd1ff9263a540145cd02a78cd3108a0774/practice_1/main.ts#L55
https://github.com/zvierievkp31ms/MIPZ/blob/bb67addd1ff9263a540145cd02a78cd3108a0774/practice_1/main.ts#L66
https://github.com/zvierievkp31ms/MIPZ/blob/bb67addd1ff9263a540145cd02a78cd3108a0774/practice_1/main.ts#L78
https://github.com/zvierievkp31ms/MIPZ/blob/bb67addd1ff9263a540145cd02a78cd3108a0774/practice_1/main.ts#L88
https://github.com/zvierievkp31ms/MIPZ/blob/bb67addd1ff9263a540145cd02a78cd3108a0774/practice_1/main.ts#L100
https://github.com/zvierievkp31ms/MIPZ/blob/bb67addd1ff9263a540145cd02a78cd3108a0774/practice_1/main.ts#L110
https://github.com/zvierievkp31ms/MIPZ/blob/bb67addd1ff9263a540145cd02a78cd3108a0774/practice_1/main.ts#L135
https://github.com/zvierievkp31ms/MIPZ/blob/bb67addd1ff9263a540145cd02a78cd3108a0774/practice_1/main.ts#L146

**Comment by zvierievkp31ms** [comment]
Added a custom radius constant and changed all hardcoded values to their usage logic based on the radius value (used values 4, 5 were based on the radius value)
