### ISSUE TITLE
Reduce code repetitiveness.

### ISSUE THREAD

**Issue by fedorchukivan** [zvierievkp31ms/MIPZ#3]
Those 3 functions use the same code for looping over matrix and only the function for calculating results differs. Could these repetitive code samples be refactored?
https://github.com/zvierievkp31ms/MIPZ/blob/bb67addd1ff9263a540145cd02a78cd3108a0774/practice_1/main.ts#L54-L63
https://github.com/zvierievkp31ms/MIPZ/blob/bb67addd1ff9263a540145cd02a78cd3108a0774/practice_1/main.ts#L134-L143
https://github.com/zvierievkp31ms/MIPZ/blob/bb67addd1ff9263a540145cd02a78cd3108a0774/practice_1/main.ts#L145-L154

**Comment by zvierievkp31ms** [comment]
Optimized the use of the code to implement traversal of the diagonal directions of the matrix, however checking the horizontal is a different task than the diagonal, so no changes are made.
