### ISSUE TITLE
For informative name for parameter

### ISSUE THREAD

**Issue by IanaKhitsko** [zvierievkp31ms/MIPZ#6]
https://github.com/zvierievkp31ms/MIPZ/blob/bb67addd1ff9263a540145cd02a78cd3108a0774/practice_1/main.ts#L41C72-L41C76

Give more informative name for "flag"

**Comment by zvierievkp31ms** [comment]
Renamed boolean function arguments to better understand the interaction of the alnorhythm with the vertical or horizontal axis or other case of main or side diagonal
