### ISSUE TITLE
Almost equal methods

### ISSUE THREAD

**Issue by IanaKhitsko** [zvierievkp31ms/MIPZ#7]
https://github.com/zvierievkp31ms/MIPZ/blob/bb67addd1ff9263a540145cd02a78cd3108a0774/practice_1/main.ts#L134

These methods are almost equal, differ only by one boolean parameter in check_diagonals

**Comment by zvierievkp31ms** [comment]
This code was fixed during the rebuild according to a issue **Reduce code repetitiveness. #3**. General Concept: A single function that takes a boolean parameter is used to understand the interaction with the matrix along the main or side diagonal
